### PR TITLE
Always use the latest pytz version

### PR DESCRIPTION
**Pull request by beaumartinez**
And enable installation using setup.py. This is a very barebones setup.py, not intended to be used to upload to PyPI, but rather to make installation easier by using the git+https link to the GitHub repo.

### CODE REVIEW

**Comment by beaumartinez** [comment]
This pull request will mean we always install the latest version of pytz (which is normally what you want, so you get the latest timezone DB), and have it automatically work on GAE—no more manually updating the code.

I also added a new arg to `build.py` to allow it to automatically copy the monkeypatched `pytz`, as if you were installing it with `pip`.

I hope it all looks good to you @brianmhunt!

**Comment by beaumartinez** [comment]
Just noticed this does not work with `pip install -e`. Let me fix that and I'll mention when it's good to merge.

**Comment by beaumartinez** [comment]
Fixed and ready to merge.

**Comment by brianmhunt** [comment]
Thanks for the PR.  Let me know if I've missed anything.

Also, I assume you know about https://code.google.com/p/googleappengine/issues/detail?id=498  (bug re. pytz coming in AppEngine ...).  Fingers crossed, and you won't need this module much longer.

Cheers

**Comment by beaumartinez** [comment]
I didn't @brianmhunt. That's great news.

**Pull request merged**
